composer/urls.py
from django.conf.urls import include, url

from . import views
app_name = 'composer'
urlpatterns = [


    url(r'^$', views.UserInsert, name='UserInsert'),
    url(r'^next/$', views.Return, name='Next'),
    url(r'^address/$', views.EnterAddress, name='EnterAddress'),
    url(r'^plants/$', views.FindProducts, name='FindProducts'),
    url(r'^support/$', views.FindSupport, name='FindSupport'),
    url(r'^maps/$', views.PlantPlacement, name='PlantPlacement'),#must change here
    url(r'^id/$', views.EnterID, name='EnterID')
]

plantsproject/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from login.views import *
import django.contrib.auth.views

# urlpatterns = [
#     url(r'^admin/', include(admin.site.urls)),
# ]

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
    url(r'^register/$', register),
    url(r'^register/success/$', register_success),
    #url(r'^home/$', home),
    #url(r'^home/', include('frontend.urls')),
    url(r'^login/$', django.contrib.auth.views.login, name='login'),
    url(r'^logout/$', django.contrib.auth.views.logout, {'next_page':'/'}, name='logout'),
    url(r'^', include('frontend.urls')),
    url(r'^composer/', include('composer.urls')),
    ]

composer/models.py
from django.db import models

class Human_Needs_Library(models.Model):
    need = models.TextField()
    type = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'Human_Needs_Library'

    def __str__(self):
        return self.need

class SPC_Project(models.Model):
    user_id = models.IntegerField()
    address = models.TextField()
    polyculture_coordinates = models.TextField()

    class Meta:
        managed = True
        db_table = 'SPC_Project'

    def __str__(self):
        return self.address

class ID_Table(models.Model):
    id = models.IntegerField(primary_key= True)
    id_Value = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'ID_Table'


class Chosen_Human_Needs(models.Model):
    project_id = models.IntegerField()
    human_need_lib_id = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'Chosen_Human_Needs'

        # def __str__(self):
        #  return self.project_id


class Chosen_Plants(models.Model):
    project_id = models.IntegerField()
    plant_id = models.IntegerField()
    key_species = models.BooleanField()

    class Meta:
        managed = True
        db_table = 'Chosen_Plants'

    def __str__(self):
        return self.plant_id

composer/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from django.forms import ModelForm, modelform_factory
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader, RequestContext
from plants.models import PlantFoodProd, Plant, PlantMedicinalsProd, PlantCulturalAndAmenityProd, PlantBiochemicalMaterialProd, PlantRawMaterialsProd, PlantMineralNutrientsProd
from .forms import Human_Needs, Address, Plants, Support, IDForm, finalPage
from django.core.urlresolvers import reverse
from django import forms
from django.core.context_processors import csrf
from django.views.generic.edit import UpdateView
from .models import ID_Table, Human_Needs_Library, SPC_Project, Chosen_Plants, Chosen_Human_Needs


UNIVERSALID = 1 #GLOBAL ID VARIABLE




#VIEW FOR MAP PLACEMENT
def PlantPlacement(request):
    addressvalues = SPC_Project.objects.order_by('id')
    currentaddress = ""

    for i in range(0, len(addressvalues), 1):
        if (addressvalues[i].user_id == UNIVERSALID):  # ADD ACTUAL USER ID HERE!!!
            currentaddress = addressvalues[i].address
            break

    #context = {'addressvalues': addressvalues}
    if request.method == 'POST':
        coordinates = request.POST.get('test', '')


        coordinatearray = []
        i = 0
        while True:
            index = coordinates.find(",", i)
            if index == -1:
                coordinatearray.append(coordinates[i:len(coordinates)])
                break
            coordinatearray.append(coordinates[i:index])
            i = index + 1

        for j in range(0, len(addressvalues), 1):
            if (addressvalues[j].user_id == UNIVERSALID and addressvalues[j].id > 0):
                addressvalues[j].polyculture_coordinates = ""
                addressvalues[j].polyculture_coordinates = coordinates
                addressvalues[j].save()
                break
        #convert string back to array
        return HttpResponseRedirect('/composer/')
    else:
        #form = Address()
        return render(request, 'composer/map.html', {"value": currentaddress})

# VIEW FOR SUPPORT SPECIES
def FindSupport(request):
    if request.method == 'POST':

        form = Support(request.POST)
        if form.is_valid():
            selectedPlants = form.cleaned_data.get('supportchoices')
            selectedId = map(int, selectedPlants)

            for i in range(0, len(selectedId), 1):
                newdata = Chosen_Plants(project_id=UNIVERSALID, plant_id=selectedId[i], key_species=False)
                newdata.save()

        return HttpResponseRedirect('/composer/next/')
    else:
        form = Support()
        return render(request, 'composer/support.html', {'form': form})


# VIEW FOR KEY SPECIES
def FindProducts(request):
    existingobjects = Chosen_Plants.objects.order_by('id')
    #a = request.session.get('a', None)

    # Task 4: Store each task into the Chosen_Plants_Table
    if request.method == 'POST':

        form = Plants(request.POST)
        if form.is_valid():
            selectedPlants = form.cleaned_data.get('plantrec')
            selectedId = map(int, selectedPlants)

            for i in range(0, len(existingobjects), 1):
                if (existingobjects[i].project_id == UNIVERSALID):
                    deletedEntry = Chosen_Plants.objects.get(id=existingobjects[i].id)
                    deletedEntry.delete()

            for i in range(0, len(selectedId), 1):
                newdata = Chosen_Plants(project_id=UNIVERSALID, plant_id= selectedId[i], key_species= True)
                newdata.save()


        return HttpResponseRedirect('/composer/support/')
    else:
        existingList = []

        form = Plants()
        return render(request, 'composer/Plants.html', {'form': form})
        #return render_to_response('composer/Plants.html', args)
    #add plants into tuple depending on what user chooses


# VIEW FOR HUMAN NEEDS
def UserInsert(request):
    #return HttpResponse("Hello, world. You're at the polls index.")
    #question = get_object_or_404(Human_Needs_Library, pk = 2)
    #selected_choice = question.choice_set.get(pk=request.POST['products'])

    chosenobjects = Chosen_Human_Needs.objects.order_by('id')
    largestid = UNIVERSALID
    #for i in range(0, len(objects), 1):  # finds largest project id value
    #    currentnumber = objects[i].project_id
    #    if currentnumber > largestid:
    #        largestid = currentnumber
    #largestid += 1

    #largestid = 1
    print request.method
    if request.method == 'POST': #add project number function

        form = Human_Needs(request.POST)

        #print largestid
        if form.is_valid():
            picked = form.cleaned_data.get('picked')


            # add functionality

            for i in range(0, len(chosenobjects), 1):
                if(chosenobjects[i].project_id == largestid):
                    deletedEntry = Chosen_Human_Needs.objects.get(id= chosenobjects[i].id)
                    deletedEntry.delete()

            picked = map(int, picked)
            for i in range(0, len(picked), 1):
                newdata = Chosen_Human_Needs(project_id=largestid, human_need_lib_id=picked[i])
                newdata.save()
            #newForm = Plants()
            print 'database created'
            #return render(request, 'composer/Plants.html', {'form': newForm})
        else:
            print 'database not created'


        #newForm = Plants()
        #return render_to_response('composer/Plants.html', {'form': newForm}, context_instance=RequestContext(request))
        return HttpResponseRedirect('/composer/plants/')

        #return render(request, 'composer/enter.html', {'form': form})


    else:
        existingList = []
        for i in range(0, len(chosenobjects), 1):
            if (chosenobjects[i].project_id == UNIVERSALID):
                existingList.append(chosenobjects[i].human_need_lib_id)
        form = Human_Needs(initial={'picked': existingList})
        return render(request, 'composer/enter.html', {'form': form})




# VIEW FOR ID PLACEHOLDER
def EnterID(request):
    if request.method == 'POST':
        IDtext = str(request.POST.get('textfield'))
        global UNIVERSALID
        UNIVERSALID = int(IDtext)
        newdata = ID_Table(id_Value= UNIVERSALID, id=1)
        newdata.save()
        return HttpResponseRedirect('/composer/address')
    else:
        form = IDForm()
        return render(request, 'composer/id.html', {'form': form})


# VIEW FOR ENTERING ADDRESS
def EnterAddress(request):
    addresstext = str(request.POST.get('textfield'))

    existingaddress = SPC_Project.objects.order_by('id')

    if request.method == 'POST':  # add project number function

        #form = Address(request.POST)
        #if form.is_valid():

        for i in range(0, len(existingaddress), 1):
            if (existingaddress[i].user_id == UNIVERSALID):
                deletedEntry = SPC_Project.objects.get(id=existingaddress[i].id)
                deletedEntry.delete()

        newAddress = SPC_Project(user_id=UNIVERSALID, address=addresstext)
        newAddress.save()


        #else:
            #print 'address not created'
            # print form

        return HttpResponseRedirect('/composer/maps')
    else:
        existingList = []
        for i in range(0, len(existingaddress), 1):
            if (existingaddress[i].user_id == UNIVERSALID):
                existingList.append(existingaddress[i].address)
        form = Address(initial={'addresstext': existingList})
        return render(request, 'composer/Address.html', {'form': form})


# VIEW FOR FINAL PAGE
def Return(request):
    form = finalPage()
    return render(request, 'composer/next.html', {'form': form})

plants/views.py
from django.shortcuts import render

# Create your views here.

composer/templates/composer/Address.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'composer/style.css' %}" />
    <meta charset="UTF-8">
    <title>Enter Address</title>
</head>
<body>
    <h1>Enter your Home Address</h1>
    <br>
    <form method = "POST">
        {% csrf_token %}
        <label>Address: </label>
        <input type="text" name="textfield"> <br>
        <input type="submit" id = "submitButton" value="Submit" />
    </form>

</body>
</html>

composer/templates/composer/Plants.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'composer/style.css' %}" />
    <meta charset="UTF-8">
    <title>Recommended Plants</title>
</head>
<body>

    <h2>Select Key Species: </h2> <br>
    <form method = "POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" id = "submitButton" value="Select Plants" />
    </form>
</body>
</html>

composer/templates/composer/UserInsert.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'composer/style.css' %}" />
    <meta charset="UTF-8">
    <title>Enter Info</title>

</head>
<body>
    <form method ="post">
        {% csrf_token %}

    <h1>Enter your info here<br></h1>
    <h2>Address</h2>
    Address layout: <input type = "text" name = "address" style = "width: 350px"> <br>
    <h2>Products</h2>
       {% for choice in latest_choice %}
            {% if choice.type == 1 %}
            <input type = "checkbox" name = "products" id = "products{{forloop.counter}}" value ="{{choice.id}}"> {{choice.need}} </br>
            {% endif %}
       {% endfor %}
    <h2>Services</h2>
       {% for choice in latest_choice %}
            {% if choice.type == 2 %}
            <input type = "checkbox" name = "services" id = "services{{forloop.counter}}" value ="{{choice.id}}"> {{choice.need}} </br>
            {% endif %}
       {% endfor %}
    <h2>Wildlife</h2>
       {% for choice in latest_choice %}
            {% if choice.type == 3 %}
            <input type = "checkbox" name = "wildlife" id = "wildlife{{forloop.counter}}" value ="{{choice.id}}"> {{choice.need}} </br>
            {% endif %}
       {% endfor %}
    <h2>Water Usage</h2>
       {% for choice in latest_choice %}
            {% if choice.type == 4 %}
            <input type = "radio" name = "water_usage" id = "water_usage{{forloop.counter}}" value ="{{choice.id}}"> {{choice.need}} </br>
            {% endif %}
       {% endfor %}
    <h2>Ecosystem Services</h2>
       {% for choice in latest_choice %}
            {% if choice.type == 5 %}
            <input type = "checkbox" name = "ecosystem_services" id = "ecosystem_services{{forloop.counter}}" value ="{{choice.id}}"> {{choice.need}} </br>
            {% endif %}
       {% endfor %}
    <br>
        {{ form.as_p }}
        {{ form.management_form }}
        <input type="submit" id = "submitButton" value="Submit" />
    </form>


</body>
</html>

composer/templates/composer/base.html
{% extends "composer/UserInsert.html" %}

{% block content %}

{% endblock %}

composer/templates/composer/enter.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'composer/style.css' %}" />
    <meta charset="UTF-8">
    <title>Title</title>

</head>
<body>
        <h1>Specify Human Needs<br></h1>
        <form method = "POST" >
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" id = "submitButton" value="Submit" />
        </form>


</body>
</html>

composer/templates/composer/id.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'composer/style.css' %}" />
    <meta charset="UTF-8">
    <title>Enter ID</title>

</head>
<body>
    <form method = "POST">
        {% csrf_token %}
        <label>Enter your ID number: </label>
        <input type="text" name="textfield"> <br>
        <input type="submit" id = "submitButton" value="Submit" />
    </form>

</body>
</html>

composer/templates/composer/map.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'composer/style.css' %}" />
    <meta charset="UTF-8">
    <title>Plant Placement</title>




    <script>var URL = "{% url 'composer:PlantPlacement' %}";</script>
    {% csrf_token %}
</head>
<body>
    <form method = "POST" >
        <input type="hidden" id="title" name="test">

    <h1>View Address</h1>
     <div>
       <label>Your entered address: {{value}}</label> <br>
       <label>Approximate Full Address, if it is completely wrong re-enter it: </label> <br>

       <input id="address" type="textbox" value="Wrong address? Re-enter it here!" style="width: 400px;">

       <input type="button" value="Encode"
              onclick='codeAddress(document.getElementById("address").value)'>

     </div>
     <div id="map_canvas" style="width: 600px; height: 480px;"></div>
     <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyBwXcI_Uyz_UYuLP_b8ImuotOqfryoJw0g"></script>
     <script type="text/javascript">


       var geocoder;
       var map;
       var test = "{{value}}";
       var allmarkers = [];
       var deletedIndexes = [];
       var connectedMarkers = [];
       var exportedMarkers = [];
       var inc = 0;
       var polyline = new google.maps.Polyline({
                path: connectedMarkers,
                strokeColor: "#0000FF",
                strokeOpacity: 0.4
       });



       function initialize() {
         geocoder = new google.maps.Geocoder();
         var address = test;
         var latlng = codeAddress(address);
         console.log(latlng);
         var fulladdress;
         var myOptions = {
           zoom: 20,
           center: latlng,
           mapTypeId: google.maps.MapTypeId.ROADMAP
         }

         map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);



         google.maps.event.addListener(map, 'click', function (e) {


            //Determine the location where the user has clicked.
            var location = e.latLng;

            //Create a marker and placed it on the map.
            var marker = new google.maps.Marker({
                position: location,
                map: map
            });




            allmarkers.push(marker);
            connectedMarkers.push({lat: location.lat(), lng: location.lng()});
            exportedMarkers.push(location.lat());
            exportedMarkers.push(location.lng());

            polyline.setPath(connectedMarkers);

            //console.log(allmarkers[0].getPosition().lat());





            google.maps.event.addListener(marker, 'rightclick', function (e){


                var currentIndex = [];
                var lineIndex = [];

                for (var i = 0; i < allmarkers.length; i++){
                    if (allmarkers[i].getPosition().lat() == location.lat()){
                        currentIndex.push(i);
                    }
                }
                for (var i = 0; i < connectedMarkers.length; i++){
                    if (connectedMarkers[i].lat == location.lat()){
                        lineIndex.push(i);
                    }
                }


                inc = 0;
                for (var i = 0; i < currentIndex.length; i++){
                    allmarkers[currentIndex[i] - inc].setMap(null);
                    allmarkers.splice(currentIndex[i] - inc, 1);

                    deletedIndexes.push(currentIndex[i] - inc);
                    inc++
                }
                inc = 0;

                for (var i = 0; i < lineIndex.length; i++){
                    connectedMarkers.splice(lineIndex[i] - inc, 1);
                    exportedMarkers.splice(lineIndex[i]*2 - inc*2, 1);
                    exportedMarkers.splice(lineIndex[i]*2 - inc*2, 1);
                    inc++
                }

                console.log(exportedMarkers);

                polyline.setPath(connectedMarkers);


                polyline.setMap(map);
            });







            polyline.setMap(map);



            document.getElementById("title").value = exportedMarkers;

            //Attach click event handler to the marker.
            google.maps.event.addListener(marker, "click", function (e) {
                var infoWindow = new google.maps.InfoWindow({
                    content: 'Latitude: ' + location.lat() + '<br />Longitude: ' + location.lng()
                });
                infoWindow.open(map, marker);
                allmarkers.push(marker);
                connectedMarkers.push({lat: location.lat(), lng: location.lng()});
                exportedMarkers.push(location.lat());
                exportedMarkers.push(location.lng());

                polyline.setPath(connectedMarkers);

            });
           });

       }

       function codeAddress(address) {
         geocoder.geocode( { 'address': address}, function(results, status) {
           if (status == google.maps.GeocoderStatus.OK) {
             map.setCenter(results[0].geometry.location);
             var latlng = {lat: results[0].geometry.location.lat(), lng: results[0].geometry.location.lng()};
             console.log(latlng);
             geocoder.geocode({'location': latlng}, function(results, status, e) {
                var fullAddress = results[1].formatted_address;
                console.log(fullAddress);
                document.getElementById("address").value = fullAddress;
             });


             var marker = new google.maps.Marker({
                 map: map,
                 position: results[0].geometry.location
             });
           } else {
             alert("Geocode was not successful for the following reason: " + status);
           }
         });

       }




       initialize();



     </script>

     <br>

         {% csrf_token %}
         {{ form.as_p }}

        <label>Instructions for creating polyculture: <br> Left Click to add a marker for polyculture perimeter <br> Right Click to delete the marker
        <br> Click on marker to connect markers and to view latitude and longitude</label> <br>


         <input type="submit" id = "submitButton" value="Submit" />
     </form>

  </body>
</html>

composer/templates/composer/next.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'composer/style.css' %}" />
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1> Thank you for submitting</h1>
    <form method = "POST" >
            {% csrf_token %}
            {{ form.as_p }}
        <input type="submit" value="Go Back" />
    </form>
</body>
</html>

composer/templates/composer/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in choice.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

composer/templates/composer/support.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load staticfiles %}
    <link rel = "stylesheet" type = "text/css" href = "{% static 'composer/style.css' %}" />
    <meta charset="UTF-8">
    <title>Support Species</title>
</head>
<body>
    <h1>Choose your support plants</h1>
    <form method = "POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" id = "submitButton" value="Select Plants" />
    </form>

</body>
</html>